config/routes.rb
Rails.application.routes.draw do
  get 'dfc_reports/index'
  get 'dre_reports/index'
  devise_for :users
  resources :financial_classes
  resources :transactions
  resources :orders
  resources :payments
  resources :guests
  resources :addresses
  resources :payment_methods
  resources :financial_accounts
  resources :hotels
  resources :rooms
  root 'dashboard#index'
  # Outras rotas podem ser adicionadas aqui
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :dre_reports, only: [:index]
  resources :dfc_reports, only: [:index]

end

app/models/address.rb
class Address < ApplicationRecord
  has_one :guest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/financial_account.rb
class FinancialAccount < ApplicationRecord
  has_many :payment_methods
  has_many :transactions
  belongs_to :hotel
  belongs_to :user
end

app/models/financial_class.rb
class FinancialClass < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address
  belongs_to :user

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, presence: true
  has_many :financial_accounts
  belongs_to :user
  has_many :payments

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :guest
  belongs_to :hotel
  belongs_to :room
  belongs_to :payment, optional: true
  belongs_to :financial_class
  belongs_to :user

  before_destroy :check_for_payment

  private

  def check_for_payment
    if payment.present?
      errors.add(:base, "Não pode deletar uma order sem antes deletar seu recebimento")
      throw(:abort)
    end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :financial_transaction, class_name: 'Transaction', dependent: :destroy, optional: true
  validates :entry_date, :execution_date, presence: true
  belongs_to :financial_class
  belongs_to :user
  belongs_to :hotel, optional: true

  validates :financial_class_id, presence: true
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :financial_account
  has_many :transactions
  validates :name, presence: true

end

app/models/report_filter.rb
# app/models/report_filter.rb
class ReportFilter
  include ActiveModel::Model

  attr_accessor :start_date, :end_date, :hotel_id, :financial_class_id, :transaction_type

  # Validações, se necessário
  validates :start_date, :end_date, presence: true

  def initialize(attributes = {})
    super
    @start_date ||= Date.today.beginning_of_month
    @end_date ||= Date.today.end_of_month
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :payment_method
  has_one :payment, dependent: :destroy
  belongs_to :financial_class
  belongs_to :user

  validates :execution_date, :transaction_type, :payment_method_id, :price, presence: true

  enum transaction_type: { income: 1, expense: 2 }

  after_create :create_payment

  private

  def create_payment
    Payment.create(
      execution_date: execution_date,
      order_id: nil,           # Ajuste conforme necessário
      transaction_id: self.id,
      price: self.price,
      financial_class_id: self.financial_class_id,
      user_id: self.user_id,
      entry_date: self.entry_date
    )
    self.update_column(:payment_id, payment.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hotels, dependent: :destroy
  has_many :financial_accounts, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :financial_classes, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_many :rooms, dependent: :destroy

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand text-white fs-2 text" href="#"><i class="fa-solid fa-hotel"></i> YourHotel</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="/"><i class="fa-solid fa-house"></i> Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="<%= guests_path %>"><i class="fa-solid fa-person-walking-luggage"></i> Hospedes</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="<%= orders_path %>"><i class="fa-solid fa-folder-plus"></i> Ordens</a>
        </li>
      </ul>
       <div class="dropdown">
        <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-briefcase"></i> Operacional
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= hotels_path %>"><i class="fa-solid fa-square-h"></i> Hoteis</a></li>
          <li><a class="dropdown-item" href="<%= rooms_path %>"><i class="fa-solid fa-person-shelter"></i> Quartos</a></li>
        </ul>
      </div>
      <div class="dropdown">
        <button class="btn btn-sm btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fa-solid fa-money-bill-trend-up"></i> Financeiro
        </button>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= financial_accounts_path %>"><i class="fa-solid fa-file-invoice"></i> Contas Financeiras</a></li>
          <li><a class="dropdown-item" href="<%= payment_methods_path %>"><i class="fa-solid fa-credit-card"></i> Formas de Pagamento</a></li>
          <li><a class="dropdown-item" href="<%= financial_classes_path %>"><i class="fa-solid fa-magnifying-glass-dollar"></i> Classes Financeiras</a></li>
          <li><a class="dropdown-item" href="<%= transactions_path %>"><i class="fa-solid fa-tent-arrow-left-right"></i> Lançamentos</a></li>
          <li><a class="dropdown-item" href="<%= payments_path %>"><i class="fa-solid fa-cash-register"></i> Pagamentos</a></li>
        </ul>
      </div>
      <a class="nav-link active text-white" aria-current="page" href="<%= dre_reports_path(start_date: Date.today.beginning_of_month, end_date: Date.today.end_of_month) %>">
        <i class="fa-solid fa-file-invoice-dollar"></i> Relatório de DRE
      </a>
      <a class="ms-2 nav-link active text-white" aria-current="page" href="<%= dfc_reports_path(start_date: Date.today.beginning_of_month, end_date: Date.today.end_of_month) %>">
        <i class="fa-solid fa-file-invoice-dollar"></i> Relatório de DFC
      </a>
    </div>
  </div>
   <div class="d-flex me-3">
        <% if user_signed_in? %>
        <div class="dropdown">
          <button class="btn btn-sm btn-primary dropdown-toggle me-5" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fa-solid fa-user-tie"></i> <%= current_user.name %>
          </button>
          <ul class="dropdown-menu">
          <li><a class="dropdown-item" href="<%= edit_user_registration_path %>"><i class="fa-solid fa-pen-to-square"></i> Editar</a></li>
          <hr class="dropdown-divider">
          <li><a class="dropdown-item" href="<%= destroy_user_session_path %>"><i class="fa-solid fa-right-from-bracket"></i> Sair</a></li>
          </ul>
        </div>
        <% else %>
          <%= link_to "Entrar", new_user_session_path, class:"btn btn-link text-white me-2 text-decoration-none" %>
          <%= link_to "Criar conta", new_user_registration_path, class:"btn btn-link text-white text-decoration-none" %>
        <% end %>
      </div>
  </nav>
<style>
.bg-primary {
    --bs-bg-opacity: 1;
    background-color: rgb(22 21 52) !important;
}
.btn-primary {
    --bs-btn-color: #fff;
    --bs-btn-bg: rgb(22 21 52) !important;;
    --bs-btn-border-color: rgb(22 21 52) !important;;
    --bs-btn-hover-color: #fff;
    --bs-btn-hover-bg: rgb(22 21 52) !important;;
    --bs-btn-hover-border-color: rgb(22 21 52) !important;;
    --bs-btn-focus-shadow-rgb: 49, 132, 253;
    --bs-btn-active-color: #fff;
    --bs-btn-active-bg: rgb(22 21 52) !important;;
    --bs-btn-active-border-color: rgb(22 21 52) !important;;
    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
    --bs-btn-disabled-color: #fff;
    --bs-btn-disabled-bg: rgb(22 21 52) !important;;
    --bs-btn-disabled-border-color: rgb(22 21 52) !important;;
}
.btn-primary-2 {
    --bs-btn-color: #fff;
    --bs-btn-bg: rgb(73 70 149) !important;
    --bs-btn-border-color: rgb(75 75 77) !important;
    --bs-btn-hover-color: #fff;
    --bs-btn-hover-bg: rgb(47 46 83) !important;
    --bs-btn-hover-border-color: rgb(20 19 30) !important;
    --bs-btn-focus-shadow-rgb: 49, 132, 253;
    --bs-btn-active-color: #fff;
    --bs-btn-active-bg: rgb(17 17 30) !important;
    --bs-btn-active-border-color: rgb(84 83 99) !important;
    --bs-btn-active-shadow: inset 0 3px 5px rgba(0, 0, 0, 0.125);
    --bs-btn-disabled-color: #fff;
    --bs-btn-disabled-bg: rgb(22 21 52) !important;
    --bs-btn-disabled-border-color: rgb(14 14 20) !important;
}
</style>

app/views/shared/_notice_alert.html.erb
<% if notice %>
  <div class="toast show align-items-center text-white bg-primary border-0" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="d-flex">
      <div class="toast-body">
        <%= notice %>
      </div>
      <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
<% end %>
<% if alert %>
    <div class="toast show align-items-center text-white bg-danger border-0" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="d-flex">
        <div class="toast-body">
          <%= alert %>
        </div>
        <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
    </div>
<% end %>