config/routes.rb
Rails.application.routes.draw do
  get 'dfc_reports/index'
  get 'dre_reports/index'
  devise_for :users
  resources :financial_classes
  resources :transactions
  resources :orders
  resources :payments
  resources :guests
  resources :addresses
  resources :payment_methods
  resources :financial_accounts
  resources :hotels
  resources :rooms
  root 'dashboard#index'
  # Outras rotas podem ser adicionadas aqui
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :dre_reports, only: [:index]
  resources :dfc_reports, only: [:index]

end

app/models/address.rb
class Address < ApplicationRecord
  has_one :guest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/financial_account.rb
class FinancialAccount < ApplicationRecord
  has_many :payment_methods
  has_many :transactions
  belongs_to :hotel
  belongs_to :user
end

app/models/financial_class.rb
class FinancialClass < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address
  belongs_to :user

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, presence: true
  has_many :financial_accounts
  belongs_to :user
  has_many :payments

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :guest
  belongs_to :hotel
  belongs_to :room
  belongs_to :payment, optional: true
  belongs_to :financial_class
  belongs_to :user

  before_destroy :check_for_payment

  private

  def check_for_payment
    if payment.present?
      errors.add(:base, "Não pode deletar uma order sem antes deletar seu recebimento")
      throw(:abort)
    end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :financial_transaction, class_name: 'Transaction', dependent: :destroy, optional: true
  validates :entry_date, :execution_date, presence: true
  belongs_to :financial_class
  belongs_to :user
  belongs_to :hotel, optional: true

  validates :financial_class_id, presence: true
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :financial_account
  has_many :transactions
  validates :name, presence: true

end

app/models/report_filter.rb
# app/models/report_filter.rb
class ReportFilter
  include ActiveModel::Model

  attr_accessor :start_date, :end_date, :hotel_id, :financial_class_id, :transaction_type

  # Validações, se necessário
  validates :start_date, :end_date, presence: true

  def initialize(attributes = {})
    super
    @start_date ||= Date.today.beginning_of_month
    @end_date ||= Date.today.end_of_month
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :payment_method
  has_one :payment, dependent: :destroy
  belongs_to :financial_class
  belongs_to :user

  validates :execution_date, :transaction_type, :payment_method_id, :price, presence: true

  enum transaction_type: { income: 1, expense: 2 }

  after_create :create_payment

  private

  def create_payment
    Payment.create(
      execution_date: execution_date,
      order_id: nil,           # Ajuste conforme necessário
      transaction_id: self.id,
      price: self.price,
      financial_class_id: self.financial_class_id,
      user_id: self.user_id,
      entry_date: self.entry_date
    )
    self.update_column(:payment_id, payment.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hotels, dependent: :destroy
  has_many :financial_accounts, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :financial_classes, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_many :rooms, dependent: :destroy

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.where(user_id: current_user.id).page(params[:page]).per(10)
  
    if params[:entry_date].present?
      @payments = @payments.where('DATE(entry_date) = ?', params[:entry_date])
    end
  
    if params[:execution_date].present?
      @payments = @payments.where('DATE(execution_date) = ?', params[:execution_date])
    end
  
    if params[:type].present?
      @payments = @payments.joins(:financial_class).where(financial_classes: { is_revenue: params[:type] == 'revenue' })
    end
  end
  
  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
    @payment.user_id = current_user.id
    if params[:order_id].present?
      @payment.order_id = params[:order_id] 
      order = Order.find(params[:order_id])
      calculate_price(order)
    end
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = current_user.payments.build(payment_params)
    if params[:payment][:order_id].present?
      order = Order.find(params[:payment][:order_id])
      @payment.financial_class_id = order.financial_class_id
      @payment.hotel_id = order.hotel_id
    end
    respond_to do |format|
      if @payment.save
        if @payment.order
          @payment.order.update!(payment_id: @payment.id)
        end
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])

    # Remover a referência ao pagamento na order antes de deletar
    @payment.order.update(payment_id: nil)

    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def calculate_price(order)
    if order.check_in_date.present? && order.check_out_date.present?
      number_of_days = (order.check_out_date - order.check_in_date).to_i + 1
      @payment.price = order.room.price * number_of_days
    end
  end

  def set_payment
    @payment = Payment.find(params[:id])
  end

  def payment_params
    params.require(:payment).permit(:entry_date, :execution_date, :order_id, :price, :financial_class_id, :hotel_id)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/dfc_reports_helper.rb
module DfcReportsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/payments/_form.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="w-50">
<div class="container mt-4">

  <%= form_with(model: @payment, local: true) do |form| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% @payment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mb-3">
    <%= form.label :execution_date, "Data de Execução", class: "form-label fw-bold" %>
    <%= form.date_field :execution_date, class: "form-control", value: @payment.execution_date || Date.today %>
  </div>
  
  <div class="mb-3">
    <%= form.label :entry_date, "Data de Entrada", class: "form-label fw-bold" %>
    <%= form.date_field :entry_date, class: "form-control" %>
  </div>



  <div class="mb-3">
    <%= form.label :price, "Preço", class: "form-label fw-bold" %>
    <%= form.number_field :price, class: "form-control", value: @payment.price %>
  </div>


  <%= form.hidden_field :order_id %> <!-- Campo oculto para order_id se presente -->

  <div class="actions">
    <%= form.submit "Salvar", class: "btn btn-primary-2" %>
  </div>
<% end %>

</div>

app/views/payments/edit.html.erb
<h1 class="text-center mt-3">Editar Recebimento</h1>

<%= render "form", payment: @payment %>

app/views/payments/index.html.erb
<div class="container mt-4">
  <h1>Lista de Recebimentos/Pagamentos</h1>

  <%= form_with url: payments_path, method: :get, local: true, class: 'mb-3' do |form| %>
    <div class="row">
      <div class="col-md-3">
        <%= form.label :entry_date, "Data de Entrada", class: "fw-bold" %>
        <%= form.date_field :entry_date, class: 'form-control', value: params[:entry_date] %>
      </div>

      <div class="col-md-3">
        <%= form.label :execution_date, "Data de Execução", class: "fw-bold" %>
        <%= form.date_field :execution_date, class: 'form-control', value: params[:execution_date] %>
      </div>

      <div class="col-md-3">
        <%= form.label :type, "Tipo", class: "fw-bold" %>
        <%= form.select :type, [['Receita', 'revenue'], ['Despesa', 'expense']], { include_blank: 'Selecione' }, class: 'form-select', selected: params[:type] %>
      </div>

      <div class="col-md-12 mt-2">
        <%= form.submit 'Filtrar', class: 'btn btn-primary' %>
        <%= link_to 'Limpar filtros', payments_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>

  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Data de Entrada</th>
          <th>Data de Execução</th>
          <th>Ordem</th>
          <th>Classe Financeira</th>
          <th>Tipo</th>
          <th>Preço</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        <% @payments.each do |payment| %>
          <tr>
            <td><%= payment.id %></td>
            <td><%= payment.entry_date.strftime("%d/%m/%Y") %></td>
            <td><%= payment.execution_date.strftime("%d/%m/%Y") %></td>
            <td><%= payment.order_id %></td>
            <td><%= payment.financial_class.name %></td>
            <td><%= payment.financial_class.is_revenue ? 'Receita' : 'Despesa' %></td>
            <td><%= number_to_currency(payment.price, unit: "R$", separator: ",", delimiter: ".", format: "%u%n") %></td>
            <td class="d-flex gap-2">
              <%= link_to 'Mostrar', payment_path(payment), class: 'btn btn-primary-2 btn-sm' %>
              <%= link_to 'Editar', edit_payment_path(payment), class: 'btn btn-primary-2 btn-sm' %>
              <%= button_to 'Excluir', payment_path(payment), method: :delete, data: { confirm: 'Tem certeza de que deseja excluir este pagamento?' }, class: 'btn btn-danger btn-sm' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @payments %>
  </div>
</div>

app/views/payments/new.html.erb
<h1 class="text-center mt-3">Novo recebimento</h1>

<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<div class="container mt-4">
  <h1>Detalhes do Pagamento</h1>

  <!-- Exibe uma mensagem de sucesso ou erro, se houver -->
  <p style="color: green"><%= notice %></p>

  <!-- Renderiza os detalhes do pagamento -->
  <div class="card">
    <div class="card-body">
      <p><strong>Data de Entrada:</strong> <%= @payment.entry_date %></p>
      <p><strong>Data de Execução:</strong> <%= @payment.execution_date %></p>
      <p><strong>Preço:</strong> <%= number_to_currency(@payment.price, unit: "R$", separator: ",", delimiter: ".", format: "%u%n") %></p>

      <!-- Link para visualizar a ordem associada -->
      <% if @payment.order %>
        <p>
          <strong>Ordem:</strong>
          <%= link_to "Visualizar Ordem ##{@payment.order_id}", order_path(@payment.order), class: 'btn btn-info btn-sm' %>
        </p>
      <% else %>
        <p><strong>Ordem:</strong> Nenhuma ordem associada</p>
      <% end %>
    </div>
  <div class="d-flex gap-2 p-2">
    <%= link_to "Editar", edit_payment_path(@payment), class: 'btn btn-primary-2 btn-sm' %> 
    <%= link_to "Voltar", payments_path, class: 'btn btn-secondary btn-sm' %>
    <%= button_to "Excluir", @payment, method: :delete, data: { confirm: 'Tem certeza de que deseja excluir este pagamento?' }, class: 'btn-sm btn btn-danger' %>
  </div>
  </div>

</div>