config/routes.rb
Rails.application.routes.draw do
  get 'dfc_reports/index'
  get 'dre_reports/index'
  devise_for :users
  resources :financial_classes
  resources :transactions
  resources :orders
  resources :payments
  resources :guests
  resources :addresses
  resources :payment_methods
  resources :financial_accounts
  resources :hotels
  resources :rooms
  root 'dashboard#index'
  # Outras rotas podem ser adicionadas aqui
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
  resources :dre_reports, only: [:index]
  resources :dfc_reports, only: [:index]

end

app/models/address.rb
class Address < ApplicationRecord
  has_one :guest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/financial_account.rb
class FinancialAccount < ApplicationRecord
  has_many :payment_methods
  has_many :transactions
  belongs_to :hotel
  belongs_to :user
end

app/models/financial_class.rb
class FinancialClass < ApplicationRecord
  belongs_to :user
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :address
  accepts_nested_attributes_for :address
  belongs_to :user

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  validates :name, presence: true
  has_many :financial_accounts
  belongs_to :user
  has_many :payments

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :guest
  belongs_to :hotel
  belongs_to :room
  belongs_to :payment, optional: true
  belongs_to :financial_class
  belongs_to :user

  before_destroy :check_for_payment

  private

  def check_for_payment
    if payment.present?
      errors.add(:base, "Não pode deletar uma order sem antes deletar seu recebimento")
      throw(:abort)
    end
  end

end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :financial_transaction, class_name: 'Transaction', dependent: :destroy, optional: true
  validates :entry_date, :execution_date, presence: true
  belongs_to :financial_class
  belongs_to :user
  belongs_to :hotel, optional: true

  validates :financial_class_id, presence: true
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :financial_account
  has_many :transactions
  validates :name, presence: true

end

app/models/report_filter.rb
# app/models/report_filter.rb
class ReportFilter
  include ActiveModel::Model

  attr_accessor :start_date, :end_date, :hotel_id, :financial_class_id, :transaction_type

  # Validações, se necessário
  validates :start_date, :end_date, presence: true

  def initialize(attributes = {})
    super
    @start_date ||= Date.today.beginning_of_month
    @end_date ||= Date.today.end_of_month
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :payment_method
  has_one :payment, dependent: :destroy
  belongs_to :financial_class
  belongs_to :user

  validates :execution_date, :transaction_type, :payment_method_id, :price, presence: true

  enum transaction_type: { income: 1, expense: 2 }

  after_create :create_payment

  private

  def create_payment
    Payment.create(
      execution_date: execution_date,
      order_id: nil,           # Ajuste conforme necessário
      transaction_id: self.id,
      price: self.price,
      financial_class_id: self.financial_class_id,
      user_id: self.user_id,
      entry_date: self.entry_date
    )
    self.update_column(:payment_id, payment.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hotels, dependent: :destroy
  has_many :financial_accounts, dependent: :destroy
  has_many :guests, dependent: :destroy
  has_many :payments, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :financial_classes, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_many :rooms, dependent: :destroy

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.jso
  def index
    @transactions = Transaction.where(user_id: current_user.id).page(params[:page]).per(10)

    if params[:execution_date].present?
      @transactions = @transactions.where('DATE(execution_date) = ?', params[:execution_date])
    end

    if params[:description].present?
      @transactions = @transactions.where('description LIKE ?', "%#{params[:description]}%")
    end

    if params[:payment_method_id].present?
      @transactions = @transactions.where(payment_method_id: params[:payment_method_id])
    end

    if params[:financial_account_id].present?
      @transactions = @transactions.joins(:payment_method).where(payment_methods: { financial_account_id: params[:financial_account_id] })
    end

    @transactions = @transactions.page(params[:page])
  end
  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new(transaction_type: params[:transaction_type])
    if params[:transaction_type] == 'income'
      @financial_classes = FinancialClass.where(is_revenue: true)
    elsif params[:transaction_type] == 'expense'
      @financial_classes = FinancialClass.where(is_revenue: false)
    else
      @financial_classes = FinancialClass.all
    end
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = current_user.transactions.build(transaction_params)
    if @transaction.financial_class.is_revenue
      @transaction.transaction_type = 1
    else
      @transaction.transaction_type = 2
    end
  binding.pry
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transaction_url(@transaction), notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy!

    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:financial_class_id, :execution_date, :transaction_type, :payment_method_id, :price, :description, :payment_id, :entry_date)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="d-flex justify-content-center align-items-center">
  <div class="w-50">
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h4 class="alert-heading">Formulário inválido:</h4>
      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :execution_date, "Data de Execução", class: "form-label fw-bold" %>
    <%= form.date_field :execution_date, class: "form-control", value: Date.today %>
  </div>


    <div class="mb-3">
    <%= form.label :entry_date, "Data de Entrada", class: "form-label fw-bold" %>
    <%= form.date_field :entry_date, class: "form-control" %>
  </div>

  <div class="mb-3">
  <%= form.label :transaction_type, "Tipo de Transação", class: "form-label fw-bold" %>
  <%= form.select :transaction_type, 
    Transaction.transaction_types.keys.map { |type| [type == 'income' ? 'Receita' : 'Despesa', type] }, 
    { prompt: "Selecione o Tipo" }, 
    class: "form-select", 
    disabled: params[:transaction_type].present? %>
</div>


  <div class="mb-3">
    <%= form.label :description, "Descrição", class: "form-label fw-bold" %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :payment_method_id, "Método de Pagamento", class: "form-label fw-bold" %>
    <%= form.collection_select :payment_method_id, PaymentMethod.joins(:financial_account).where(financial_accounts: { user_id: current_user.id }), :id, :name, { prompt: "Selecione um Método de Pagamento" }, class: "form-select" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, "Preço", class: "form-label fw-bold" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :financial_class_id, "Classe Financeira", class: "form-label fw-bold" %>
    <%= form.collection_select :financial_class_id, @financial_classes, :id, :name,{  prompt: "Selecione a Classe Financeira" }, class: "form-select" %>
  </div>


  <div class="mb-3">
    <%= form.submit "Salvar", class: "btn btn-primary-2 btn-sm" %>
    <%= link_to "Voltar", transactions_path, class: "btn btn-secondary btn-sm" %>
  </div>
  </div>
  </div>
<% end %>

app/views/transactions/_transaction.html.erb
<div id="<%= dom_id transaction %>">
  <p>
    <strong>Execution date:</strong>
    <%= transaction.execution_date %>
  </p>

  <p>
    <strong>Transaction type:</strong>
    <%= transaction.transaction_type %>
  </p>

  <p>
    <strong>Payment:</strong>
    <%= transaction.payment_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= transaction.description %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= transaction.payment_method_id %>
  </p>

  <p>
    <strong>Financial account:</strong>
    <%= transaction.payment_method.financial_account_id %>
  </p>

</div>

app/views/transactions/edit.html.erb
<h1 class="text-center mt-3">Editar lançamento</h1>

<%= render "form", transaction: @transaction %>

app/views/transactions/index.html.erb
<div class="container mt-5">
  <h1>Lançamentos</h1>

 <%= form_with url: transactions_path, method: :get, local: true, class: 'mb-3' do |form| %>
    <div class="row">
      <div class="col-md-3">
        <%= form.label :execution_date, "Data de execução", class: "fw-bold" %>
        <%= form.date_field :execution_date, class: 'form-control', value: params[:execution_date] %>
      </div>

      <div class="col-md-3">
        <%= form.label :description, "Descrição", class: "fw-bold" %>
        <%= form.text_field :description, class: 'form-control', value: params[:description] %>
      </div>

      <div class="col-md-3">
        <%= form.label :payment_method_id, "Forma de pagamento", class: "fw-bold" %>
        <%= form.select :payment_method_id, PaymentMethod.pluck(:name, :id), { include_blank: 'Selecione' }, class: 'form-select', selected: params[:payment_method_id] %>
      </div>

      <div class="col-md-3">
        <%= form.label :financial_account_id, "Conta Financeira", class: "fw-bold" %>
        <%= form.select :financial_account_id, FinancialAccount.pluck(:bank, :id), { include_blank: 'Selecione' }, class: 'form-select', selected: params[:financial_account_id] %>
      </div>

      <div class="col-md-12 mt-2">
        <%= form.submit 'Filtrar', class: 'btn btn-primary' %>
        <%= link_to 'Limpar filtros', transactions_path, class: 'btn btn-secondary' %>
      </div>
    </div>
  <% end %>

  <p>
    <%= link_to 'Nova Receita', new_transaction_path(transaction_type: 'income'), class: 'btn btn-sm btn-success' %>
    <%= link_to 'Nova Despesa', new_transaction_path(transaction_type: 'expense'), class: 'btn btn-sm btn-danger' %>
  </p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th class="text-nowrap">Data de execução</th>
        <th class="text-nowrap">Tipo de transação</th>
        <th>Descrição</th>
        <th class="text-nowrap">Classe Financeira</th>
        <th class="text-nowrap">Forma de pagamento</th>
        <th class="text-nowrap">Conta Financeira</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.id %></td>
          <td><%= transaction.execution_date.strftime("%d/%m/%Y") %></td>
          <td><%= transaction.transaction_type == 'income' ? 'Receita' : 'Despesa' %></td>
          <td ><%= transaction.description %></td>
          <td><%= transaction.financial_class ? transaction.financial_class.name : "" %></td>
          <td><%= transaction.payment_method.name %></td>
          <td><%= transaction.payment_method.financial_account.bank %></td>
          <td class="d-flex gap-2">
            <%= link_to 'Mostrar', transaction_path(transaction), class: 'btn btn-primary-2 btn-sm' %>
            <%= link_to 'Editar', edit_transaction_path(transaction), class: 'btn btn-primary-2 btn-sm' %>
            <%= button_to 'Deletar', transaction_path(transaction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @transactions %>
</div>

app/views/transactions/new.html.erb
<h1 class="text-center mt-3">Novo Lançamento</h1>

<%= render "form", transaction: @transaction %>

app/views/transactions/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mt-5">

<div class="card">
  <div class="card-header">
    <h3 class="card-title">Detalhes da Transação</h3>
  </div>
  <div class="card-body">
    <p>
      <strong>Data de Execução:</strong>
      <%= @transaction.execution_date %>
    </p>

    <p>
      <strong>Tipo de Transação:</strong>
      <%= @transaction.transaction_type.humanize %>
    </p>

    <p>
      <strong>Descrição:</strong>
      <%= @transaction.description %>
    </p>

    <p>
      <strong>Metodo de Pagamento:</strong>
      <%= @transaction.payment_method.name %>
    </p>

    <p>
      <strong>Preço:</strong>
      <%= number_to_currency(@transaction.price, unit: "R$", delimiter: ".", separator: ",") %>
    </p>

    <p>
      <strong>ID do Pagamento:</strong>
      <%= @transaction.payment_id if @transaction.payment.present? %>
    </p>
  </div>
  <div class="d-flex gap-2 p-2">
    <%= link_to "Editar", edit_transaction_path(@transaction), class: "btn btn-primary-2 btn-sm" %>
    <%= link_to "Voltar", transactions_path, class: "btn btn-secondary btn-sm" %>
    <%= button_to "Deletar", @transaction, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm" %>
  </div>
</div>
</div>